# -*- coding: utf-8 -*-
__title__ = "Rename Views"
__doc__ = """Version = 1.0
Date    = 19.08.2025
_____________________________________________________________________
Description:
Rename Views in Revit by using Find/Replace Logic.
_____________________________________________________________________
How-to:
-> Click on the button
-> Select Views
-> Define Renaming Rules
-> Rename Views
_____________________________________________________________________
Last update:
- [19.08.2025] - 1.0 RELEASE
_____________________________________________________________________
Author: Nam Pham"""

# â•¦â•”â•¦â•—â•”â•â•—â•”â•â•—â•¦â•â•—â•”â•¦â•—â•”â•â•—
# â•‘â•‘â•‘â•‘â• â•â•â•‘ â•‘â• â•¦â• â•‘ â•šâ•â•—
# â•©â•© â•©â•©  â•šâ•â•â•©â•šâ• â•© â•šâ•â• IMPORTS
#==================================================
# Regular + Autodesk
from Autodesk.Revit.DB import *

# pyRevit
from pyrevit import revit, forms

# .NET Imports (You often need List import)
import clr
clr.AddReference("System")
from System.Collections.Generic import List

# â•¦  â•¦â•”â•â•—â•¦â•â•—â•¦â•”â•â•—â•”â•— â•¦  â•”â•â•—â•”â•â•—
# â•šâ•—â•”â•â• â•â•£â• â•¦â•â•‘â• â•â•£â• â•©â•—â•‘  â•‘â•£ â•šâ•â•—
#  â•šâ• â•© â•©â•©â•šâ•â•©â•© â•©â•šâ•â•â•©â•â•â•šâ•â•â•šâ•â• VARIABLES
#==================================================
doc   = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument
app   = __revit__.Application

# â•”â•â•—â•¦ â•¦â•”â•—â•”â•”â•â•—â•”â•¦â•—â•¦â•”â•â•—â•”â•—â•”â•”â•â•—
# â• â•£ â•‘ â•‘â•‘â•‘â•‘â•‘   â•‘ â•‘â•‘ â•‘â•‘â•‘â•‘â•šâ•â•—
# â•š  â•šâ•â•â•â•šâ•â•šâ•â• â•© â•©â•šâ•â•â•â•šâ•â•šâ•â•
#==================================================

# â•”â•¦â•—â•”â•â•—â•¦â•”â•—â•”
# â•‘â•‘â•‘â• â•â•£â•‘â•‘â•‘â•‘
# â•© â•©â•© â•©â•©â•â•šâ• MAIN
#==================================================
# 1ï¸âƒ£ Select Views

sel_id = uidoc.Selection.GetElementIds()
sel_element = [doc.GetElement(e_id) for e_id in sel_id]
sel_view = [e for e in sel_element if issubclass(type(e), View)]

# If None Selected - Promt SelectViews from pyrevit.forms.select_views()
if not sel_view:
    sel_view= forms.select_views()

#Ensure Views Selected
if not sel_view:
    forms.alert("No views selected. Please try again", exitscript=True)

#2ï¸âƒ£ðŸ…°ï¸ Define Renaming Rules

#prefix  = 'pre - '
#find    = 'Level'
#replace = 'FloorPlan'
#suffix  = ' - suf'

#2ï¸âƒ£ðŸ…±ï¸ Define Renaming Rules (UI FORM)
#https://revitpythonwrapper.readthedocs.io/en/latest/ui/forms.html#flexform

from rpw.ui.forms import (FlexForm, Label, TextBox, Separator, Button, CheckBox)
components =    [Label('Prefix:'), TextBox ('prefix'),
                Label('Find:'), TextBox ('find'),
                Label('Replace:'), TextBox ('replace'),
                Label('Suffix:'), TextBox ('suffix'),
                Separator(),           Button('Renaming Views')]

form = FlexForm('Rename Views', components)
form.show()

user_inputs = form.values
prefix  = user_inputs['prefix']
find  = user_inputs['find']
replace    = user_inputs['replace']
suffix = user_inputs['suffix']

# ðŸ”’ Start Transaction to make changes in project
t = Transaction(doc, 'Rename Views')

t.Start()   #ðŸ”“

# 3ï¸âƒ£Create new View Name
for view in sel_view:
    old_name = view.Name
    new_name = prefix + old_name.replace(find, replace) + suffix

    #4ï¸âƒ£ Ensure Views (Ensure unique View Name)
    for i in range(20):
        try:
            view.Name = new_name #âœ…This actually renames the views
            print('{} -> {}'.format(old_name, new_name))
            break
        except:
            new_name += '*'

t.Commit()  #ðŸ”’

print('-'*50)
print('Done!')